name: ERC4337 Indexer
description: ERC4337 Account and Module Indexer
contracts:
  - name: EntryPointV0_6_0
    abi_file_path: ./abi/entryPointV0_6_0.json
    handler: ./src/entryPoint.ts
    events:
      - event: UserOperationEvent(bytes32 indexed userOpHash, address indexed sender, address indexed paymaster, uint256 nonce, bool success, uint256 actualGasCost, uint256 actualGasUsed)
      - event: AccountDeployed(bytes32 indexed userOpHash, address indexed sender, address factory, address paymaster)
  - name: EntryPointV0_7_0
    abi_file_path: ./abi/entryPointV0_7_0.json
    handler: ./src/entryPoint.ts
    events:
      - event: UserOperationEvent(bytes32 indexed userOpHash, address indexed sender, address indexed paymaster, uint256 nonce, bool success, uint256 actualGasCost, uint256 actualGasUsed)
      - event: AccountDeployed(bytes32 indexed userOpHash, address indexed sender, address factory, address paymaster)
field_selection:
  transaction_fields:
    - transactionIndex
    - hash
    - from
unordered_multichain_mode: true
rollback_on_reorg: false
networks:
  - id: 1
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 11155111
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 10
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 11155420
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 137
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 80002
    hypersync_config:
      endpoint_url: "https://amoy.hypersync.xyz"
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 8453
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 84532
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 42161
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 421614
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 34443
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 59144
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 42170
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 42220
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 43114
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 43113
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 100
    start_block: 0
    contracts:
      - name: EntryPointV0_6_0
        address: "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
      - name: EntryPointV0_7_0
        address: "0x0000000071727de22e5e9d8baf0edac6f37da032"
