name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Clean install
        run: bun install

      - name: Codegen
        run: bun run codegen

      - name: Build
        run: bun run build
